# Generated by Django 5.1.7 on 2025-04-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
